package net.sevenscales.editor.api;

public enum EditorProperty {
	CURRENT_RELATIONSHIP_TYPE,
	AUTO_RESIZE_ENABLED, 
	PROPERTY_EDITOR_SELECT_ALL_ENABLED, 
	PROPERTY_EDITOR_REPLACE_TEXT,
	ON_CHANGE_ENABLED,
	ON_OT_OPERATION,
	SKETCHO_BOARD_MODE, 
	ON_SURFACE_LOAD,
	CURRENT_LIBRARY,
	CURRENT_COLOR,
	FREEHAND_MODE,
	FREEHAND_MODE_TYPE,
	FREEHAND_MOUSE_DOWN,
	RESOURCES_PATH, 
	CONFLUENCE_MODE, 
	START_SELECTION_TOOL,
	PROPERTY_EDITOR_IS_OPEN;
}
