dev:
	cp src/main/java/net/sevenscales/sketchoconfluenceapp/Sketcho_confluence_app.gwt-dev.xml \
	   src/main/java/net/sevenscales/sketchoconfluenceapp/Sketcho_confluence_app.gwt.xml
	ant dev
	./codeserver.sh 

prod:
	cp src/main/java/net/sevenscales/sketchoconfluenceapp/Sketcho_confluence_app.gwt-prod.xml \
	   src/main/java/net/sevenscales/sketchoconfluenceapp/Sketcho_confluence_app.gwt.xml
	ant prod